# Site settings
title: Fallen Cougars
email: your-email@domain.com
url: https://alexmerrill.github.io/veterans
description: "The WSU-WSC WWII Commemoration Project"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  #links: '#981e32'
  links: '#fff'

# Footer settings
footer:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/IronSummitMedia/startbootstrap

# Build settings
markdown: kramdown
permalink: pretty
